version: '3' # docker-composeの使用バージョン
services:    # 「作られるサービスの設定を以下に記載します」の意味
  nginx:     # コンテナネーム(注1)
    build: ./nginx  # Dockerfileの場所
    ports:
      - "8080:80"
    volumes:
      - ./lab:/usr/share/nginx/html
